// @generated by protoc-gen-es v1.9.0 with parameter "target=js+dts"
// @generated from file helloworld/v1/helloworld.proto (package helloworld.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message helloworld.v1.HelloWorldRequest
 */
export const HelloWorldRequest = /*@__PURE__*/ proto3.makeMessageType(
  "helloworld.v1.HelloWorldRequest",
  [],
);

/**
 * @generated from message helloworld.v1.HelloWorldResponse
 */
export const HelloWorldResponse = /*@__PURE__*/ proto3.makeMessageType(
  "helloworld.v1.HelloWorldResponse",
  () => [
    { no: 1, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

