// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file helloworld/v1/helloworld.proto (package helloworld.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { HelloWorldRequest, HelloWorldResponse } from "./helloworld_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service helloworld.v1.HelloWorldService
 */
export const HelloWorldService = {
  typeName: "helloworld.v1.HelloWorldService",
  methods: {
    /**
     * @generated from rpc helloworld.v1.HelloWorldService.HelloWorld
     */
    helloWorld: {
      name: "HelloWorld",
      I: HelloWorldRequest,
      O: HelloWorldResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

