// @generated by protoc-gen-es v1.9.0 with parameter "target=js+dts"
// @generated from file what2do/v1/recommendations.proto (package what2do.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage, Timestamp } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum what2do.v1.EventType
 */
export declare enum EventType {
  /**
   * @generated from enum value: EVENT_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: EVENT_TYPE_RESTAURANT = 1;
   */
  RESTAURANT = 1,

  /**
   * @generated from enum value: EVENT_TYPE_ACTIVITY = 2;
   */
  ACTIVITY = 2,
}

/**
 * @generated from message what2do.v1.Recommendation
 */
export declare class Recommendation extends Message<Recommendation> {
  /**
   * @generated from field: int32 rank = 1;
   */
  rank: number;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * make address into the international standard as object
   *
   * @generated from field: string address = 3;
   */
  address: string;

  /**
   * @generated from field: string PriceLevel = 4;
   */
  PriceLevel: string;

  /**
   * @generated from field: google.protobuf.Timestamp Open = 5;
   */
  Open?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp Close = 6;
   */
  Close?: Timestamp;

  constructor(data?: PartialMessage<Recommendation>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "what2do.v1.Recommendation";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Recommendation;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Recommendation;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Recommendation;

  static equals(a: Recommendation | PlainMessage<Recommendation> | undefined, b: Recommendation | PlainMessage<Recommendation> | undefined): boolean;
}

/**
 * @generated from message what2do.v1.SearchRecommendationsRequest
 */
export declare class SearchRecommendationsRequest extends Message<SearchRecommendationsRequest> {
  /**
   * @generated from field: google.protobuf.Timestamp event_time = 1;
   */
  eventTime?: Timestamp;

  /**
   * @generated from field: string location = 2;
   */
  location: string;

  /**
   * @generated from field: what2do.v1.EventType event_type = 3;
   */
  eventType: EventType;

  /**
   * @generated from field: string search_param = 4;
   */
  searchParam: string;

  constructor(data?: PartialMessage<SearchRecommendationsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "what2do.v1.SearchRecommendationsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SearchRecommendationsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SearchRecommendationsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SearchRecommendationsRequest;

  static equals(a: SearchRecommendationsRequest | PlainMessage<SearchRecommendationsRequest> | undefined, b: SearchRecommendationsRequest | PlainMessage<SearchRecommendationsRequest> | undefined): boolean;
}

/**
 * @generated from message what2do.v1.SearchRecommendationsResponse
 */
export declare class SearchRecommendationsResponse extends Message<SearchRecommendationsResponse> {
  /**
   * @generated from field: repeated what2do.v1.Recommendation recommendations = 1;
   */
  recommendations: Recommendation[];

  constructor(data?: PartialMessage<SearchRecommendationsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "what2do.v1.SearchRecommendationsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SearchRecommendationsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SearchRecommendationsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SearchRecommendationsResponse;

  static equals(a: SearchRecommendationsResponse | PlainMessage<SearchRecommendationsResponse> | undefined, b: SearchRecommendationsResponse | PlainMessage<SearchRecommendationsResponse> | undefined): boolean;
}

