// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file what2do/v1/service.proto (package what2do.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

/**
 * @generated from service what2do.v1.What2DoService
 */
export const What2DoService = {
  typeName: "what2do.v1.What2DoService",
  methods: {
  }
} as const;

