// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file what2do/v1/service.proto (package what2do.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { SearchRecommendationsRequest, SearchRecommendationsResponse } from "./recommendations_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { CreateEventRequest, CreateEventResponse, GetEventRequest, GetEventResponse } from "./event_pb.js";

/**
 * @generated from service what2do.v1.What2DoService
 */
export const What2DoService = {
  typeName: "what2do.v1.What2DoService",
  methods: {
    /**
     * @generated from rpc what2do.v1.What2DoService.SearchRecommendations
     */
    searchRecommendations: {
      name: "SearchRecommendations",
      I: SearchRecommendationsRequest,
      O: SearchRecommendationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc what2do.v1.What2DoService.CreateEvent
     */
    createEvent: {
      name: "CreateEvent",
      I: CreateEventRequest,
      O: CreateEventResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc what2do.v1.What2DoService.GetEvent
     */
    getEvent: {
      name: "GetEvent",
      I: GetEventRequest,
      O: GetEventResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

