// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: what2do/v1/recommendations.proto

package what2do_protobufs_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_EVENT_TYPE_RESTAURANT  EventType = 1
	EventType_EVENT_TYPE_ACTIVITY    EventType = 2
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_RESTAURANT",
		2: "EVENT_TYPE_ACTIVITY",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"EVENT_TYPE_RESTAURANT":  1,
		"EVENT_TYPE_ACTIVITY":    2,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_what2do_v1_recommendations_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_what2do_v1_recommendations_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_what2do_v1_recommendations_proto_rawDescGZIP(), []int{0}
}

type Recommendation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rank int32  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// make address into the international standard as object
	Address    string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	PriceLevel string                 `protobuf:"bytes,4,opt,name=PriceLevel,proto3" json:"PriceLevel,omitempty"`
	Open       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=Open,proto3" json:"Open,omitempty"`
	Close      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=Close,proto3" json:"Close,omitempty"`
}

func (x *Recommendation) Reset() {
	*x = Recommendation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_what2do_v1_recommendations_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Recommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recommendation) ProtoMessage() {}

func (x *Recommendation) ProtoReflect() protoreflect.Message {
	mi := &file_what2do_v1_recommendations_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recommendation.ProtoReflect.Descriptor instead.
func (*Recommendation) Descriptor() ([]byte, []int) {
	return file_what2do_v1_recommendations_proto_rawDescGZIP(), []int{0}
}

func (x *Recommendation) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *Recommendation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Recommendation) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Recommendation) GetPriceLevel() string {
	if x != nil {
		return x.PriceLevel
	}
	return ""
}

func (x *Recommendation) GetOpen() *timestamppb.Timestamp {
	if x != nil {
		return x.Open
	}
	return nil
}

func (x *Recommendation) GetClose() *timestamppb.Timestamp {
	if x != nil {
		return x.Close
	}
	return nil
}

type SearchRecommendationsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventTime   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	Location    string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	EventType   EventType              `protobuf:"varint,3,opt,name=event_type,json=eventType,proto3,enum=what2do.v1.EventType" json:"event_type,omitempty"`
	SearchParam string                 `protobuf:"bytes,4,opt,name=search_param,json=searchParam,proto3" json:"search_param,omitempty"`
}

func (x *SearchRecommendationsRequest) Reset() {
	*x = SearchRecommendationsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_what2do_v1_recommendations_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRecommendationsRequest) ProtoMessage() {}

func (x *SearchRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_what2do_v1_recommendations_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*SearchRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_what2do_v1_recommendations_proto_rawDescGZIP(), []int{1}
}

func (x *SearchRecommendationsRequest) GetEventTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTime
	}
	return nil
}

func (x *SearchRecommendationsRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *SearchRecommendationsRequest) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *SearchRecommendationsRequest) GetSearchParam() string {
	if x != nil {
		return x.SearchParam
	}
	return ""
}

type SearchRecommendationsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recommendations []*Recommendation `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
}

func (x *SearchRecommendationsResponse) Reset() {
	*x = SearchRecommendationsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_what2do_v1_recommendations_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRecommendationsResponse) ProtoMessage() {}

func (x *SearchRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_what2do_v1_recommendations_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*SearchRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_what2do_v1_recommendations_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRecommendationsResponse) GetRecommendations() []*Recommendation {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

var File_what2do_v1_recommendations_proto protoreflect.FileDescriptor

var file_what2do_v1_recommendations_proto_rawDesc = []byte{
	0x0a, 0x20, 0x77, 0x68, 0x61, 0x74, 0x32, 0x64, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x77, 0x68, 0x61, 0x74, 0x32, 0x64, 0x6f, 0x2e, 0x76, 0x31, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xd4, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x12, 0x2e, 0x0a, 0x04, 0x4f, 0x70, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04,
	0x4f, 0x70, 0x65, 0x6e, 0x12, 0x30, 0x0a, 0x05, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x05, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x22, 0xce, 0x01, 0x0a, 0x1c, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x34,
	0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x15, 0x2e, 0x77, 0x68, 0x61, 0x74, 0x32, 0x64, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x22, 0x65, 0x0a, 0x1d, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0f, 0x72, 0x65, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x77, 0x68, 0x61, 0x74, 0x32, 0x64, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0f, 0x72,
	0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2a, 0x5b,
	0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x45,
	0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x45, 0x56, 0x45, 0x4e, 0x54,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x54, 0x41, 0x55, 0x52, 0x41, 0x4e, 0x54,
	0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x49, 0x54, 0x59, 0x10, 0x02, 0x42, 0x2d, 0x5a, 0x2b, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x6f, 0x70, 0x2d, 0x63,
	0x6d, 0x70, 0x65, 0x72, 0x73, 0x2f, 0x77, 0x68, 0x61, 0x74, 0x32, 0x64, 0x6f, 0x2d, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2d, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_what2do_v1_recommendations_proto_rawDescOnce sync.Once
	file_what2do_v1_recommendations_proto_rawDescData = file_what2do_v1_recommendations_proto_rawDesc
)

func file_what2do_v1_recommendations_proto_rawDescGZIP() []byte {
	file_what2do_v1_recommendations_proto_rawDescOnce.Do(func() {
		file_what2do_v1_recommendations_proto_rawDescData = protoimpl.X.CompressGZIP(file_what2do_v1_recommendations_proto_rawDescData)
	})
	return file_what2do_v1_recommendations_proto_rawDescData
}

var file_what2do_v1_recommendations_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_what2do_v1_recommendations_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_what2do_v1_recommendations_proto_goTypes = []interface{}{
	(EventType)(0),                        // 0: what2do.v1.EventType
	(*Recommendation)(nil),                // 1: what2do.v1.Recommendation
	(*SearchRecommendationsRequest)(nil),  // 2: what2do.v1.SearchRecommendationsRequest
	(*SearchRecommendationsResponse)(nil), // 3: what2do.v1.SearchRecommendationsResponse
	(*timestamppb.Timestamp)(nil),         // 4: google.protobuf.Timestamp
}
var file_what2do_v1_recommendations_proto_depIdxs = []int32{
	4, // 0: what2do.v1.Recommendation.Open:type_name -> google.protobuf.Timestamp
	4, // 1: what2do.v1.Recommendation.Close:type_name -> google.protobuf.Timestamp
	4, // 2: what2do.v1.SearchRecommendationsRequest.event_time:type_name -> google.protobuf.Timestamp
	0, // 3: what2do.v1.SearchRecommendationsRequest.event_type:type_name -> what2do.v1.EventType
	1, // 4: what2do.v1.SearchRecommendationsResponse.recommendations:type_name -> what2do.v1.Recommendation
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_what2do_v1_recommendations_proto_init() }
func file_what2do_v1_recommendations_proto_init() {
	if File_what2do_v1_recommendations_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_what2do_v1_recommendations_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Recommendation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_what2do_v1_recommendations_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchRecommendationsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_what2do_v1_recommendations_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchRecommendationsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_what2do_v1_recommendations_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_what2do_v1_recommendations_proto_goTypes,
		DependencyIndexes: file_what2do_v1_recommendations_proto_depIdxs,
		EnumInfos:         file_what2do_v1_recommendations_proto_enumTypes,
		MessageInfos:      file_what2do_v1_recommendations_proto_msgTypes,
	}.Build()
	File_what2do_v1_recommendations_proto = out.File
	file_what2do_v1_recommendations_proto_rawDesc = nil
	file_what2do_v1_recommendations_proto_goTypes = nil
	file_what2do_v1_recommendations_proto_depIdxs = nil
}
