// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: what2do/v1/recommendations.proto

package what2do_protobufs_go

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Recommendation with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Recommendation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Recommendation with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RecommendationMultiError,
// or nil if none found.
func (m *Recommendation) ValidateAll() error {
	return m.validate(true)
}

func (m *Recommendation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Rank

	// no validation rules for Address

	// no validation rules for Description

	if len(errors) > 0 {
		return RecommendationMultiError(errors)
	}

	return nil
}

// RecommendationMultiError is an error wrapping multiple validation errors
// returned by Recommendation.ValidateAll() if the designated constraints
// aren't met.
type RecommendationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RecommendationMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RecommendationMultiError) AllErrors() []error { return m }

// RecommendationValidationError is the validation error returned by
// Recommendation.Validate if the designated constraints aren't met.
type RecommendationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RecommendationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RecommendationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RecommendationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RecommendationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RecommendationValidationError) ErrorName() string { return "RecommendationValidationError" }

// Error satisfies the builtin error interface
func (e RecommendationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRecommendation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RecommendationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RecommendationValidationError{}

// Validate checks the field values on SearchRecommendationsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SearchRecommendationsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SearchRecommendationsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SearchRecommendationsRequestMultiError, or nil if none found.
func (m *SearchRecommendationsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SearchRecommendationsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetEventTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SearchRecommendationsRequestValidationError{
					field:  "EventTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SearchRecommendationsRequestValidationError{
					field:  "EventTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEventTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SearchRecommendationsRequestValidationError{
				field:  "EventTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Location

	// no validation rules for EventType

	// no validation rules for SearchParam

	if len(errors) > 0 {
		return SearchRecommendationsRequestMultiError(errors)
	}

	return nil
}

// SearchRecommendationsRequestMultiError is an error wrapping multiple
// validation errors returned by SearchRecommendationsRequest.ValidateAll() if
// the designated constraints aren't met.
type SearchRecommendationsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SearchRecommendationsRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SearchRecommendationsRequestMultiError) AllErrors() []error { return m }

// SearchRecommendationsRequestValidationError is the validation error returned
// by SearchRecommendationsRequest.Validate if the designated constraints
// aren't met.
type SearchRecommendationsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SearchRecommendationsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SearchRecommendationsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SearchRecommendationsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SearchRecommendationsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SearchRecommendationsRequestValidationError) ErrorName() string {
	return "SearchRecommendationsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SearchRecommendationsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSearchRecommendationsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SearchRecommendationsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SearchRecommendationsRequestValidationError{}

// Validate checks the field values on SearchRecommendationsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SearchRecommendationsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SearchRecommendationsResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// SearchRecommendationsResponseMultiError, or nil if none found.
func (m *SearchRecommendationsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SearchRecommendationsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetRecommendation() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SearchRecommendationsResponseValidationError{
						field:  fmt.Sprintf("Recommendation[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SearchRecommendationsResponseValidationError{
						field:  fmt.Sprintf("Recommendation[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SearchRecommendationsResponseValidationError{
					field:  fmt.Sprintf("Recommendation[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return SearchRecommendationsResponseMultiError(errors)
	}

	return nil
}

// SearchRecommendationsResponseMultiError is an error wrapping multiple
// validation errors returned by SearchRecommendationsResponse.ValidateAll()
// if the designated constraints aren't met.
type SearchRecommendationsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SearchRecommendationsResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SearchRecommendationsResponseMultiError) AllErrors() []error { return m }

// SearchRecommendationsResponseValidationError is the validation error
// returned by SearchRecommendationsResponse.Validate if the designated
// constraints aren't met.
type SearchRecommendationsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SearchRecommendationsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SearchRecommendationsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SearchRecommendationsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SearchRecommendationsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SearchRecommendationsResponseValidationError) ErrorName() string {
	return "SearchRecommendationsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SearchRecommendationsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSearchRecommendationsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SearchRecommendationsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SearchRecommendationsResponseValidationError{}
